FROM node:25-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN apk add --no-cache build-base ca-certificates tzdata \
    && npm install \
    && npm run build
COPY . .


FROM node:25-alpine
WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/server.js ./ 

EXPOSE 3000
ENV NODE_ENV=production
USER root
CMD ["node", "dist/server.js"]